### PR TITLE
Refactor xenvmd/local-allocator into manageable chunks

### PR DESCRIPTION
**Pull request by jonludlam**
Removes cut+pasted code, and breaks out functionality into smaller, more well defined modules with stricter interfaces.

### CODE REVIEW

**Comment by jonludlam** [comment]
Not thoroughly tested yet - PR is for review.

**Comment by simonjbeaumont** [comment]
32 commits.... 32?!

**Comment by djs55** [comment]
It's important to have a large number of commits-- I approve ;-)

**Comment by simonjbeaumont** [comment]
> It's important to have a large number of commits-- I approve ;-)

Says the guy who's no longer on the hook for review! ;) Nice to hear from you @djs55

**Pull request merged**
