### PR TITLE
CP-13469: Add upgrade/downgrade CLI support

### PR DESCRIPTION
**Pull request by simonjbeaumont**
This series adds support for upgrading and downgrading between legacy LVM2 and XenVM VGs. The commands are designed to be idempotent and transactional.

### CODE REVIEW

**Comment by djs55** [comment]
Looks good. Out of curiosity, did you manually test holding the LVM lock successfully stopped an LVM command from running?

**Comment by simonjbeaumont** [comment]
I did... the following hangs:

```
$ flock /run/lock/lvm/V_VG_XenStorage-a02b611d-cb72-79c8-840f-a432770b4d55:aux vgs
```

It won't, however, protect us against the use of the `--ignorelockingfailure` option that the LVM commands accept. I'm pretty sure we don't (read shouldn't) use these in the product.

**Comment by djs55** [comment]
OK, does holding that lock (with flock) definitely block 'lvs' from running? I'm happy if so!

**Comment by simonjbeaumont** [comment]
@djs55: This looks good:

```
[root@dt04 ~]# flock /run/lock/lvm/V_VG_XenStorage-a02b611d-cb72-79c8-840f-a432770b4d55:aux lvs
File descriptor 3 (/run/lock/lvm/V_VG_XenStorage-a02b611d-cb72-79c8-840f-a432770b4d55:aux) leaked on lvs invocation. Parent PID 10379: flock
^C  CTRL-c detected: giving up waiting for lock

[root@dt04 ~]#   /run/lock/lvm/V_VG_XenStorage-a02b611d-cb72-79c8-840f-a432770b4d55:aux: flock failed: Interrupted system call
  Can't get lock for VG_XenStorage-a02b611d-cb72-79c8-840f-a432770b4d55
  Skipping volume group VG_XenStorage-a02b611d-cb72-79c8-840f-a432770b4d55
^C
[root@dt04 ~]# lvs
  LV   VG                                                 Attr       LSize Pool Origin Data%  Move Log Cpy%Sync Convert
  MGT  VG_XenStorage-a02b611d-cb72-79c8-840f-a432770b4d55 -wi-a----- 4.00m
[root@dt04 ~]# 
```

**Comment by djs55** [comment]
Sounds good to me!

**Pull request merged**
