### PR TITLE
Run local allocator tests using mock device mapper

### PR DESCRIPTION
**Pull request by simonjbeaumont**
Signed-off-by: Si Beaumont simon.beaumont@citrix.com

### CODE REVIEW

**Comment by simonjbeaumont** [comment]
@jonludlam says this is good.

**Comment by jonludlam** [comment]
But Travis says it's bad. Is that because the new device mapper library hasn't been released yet?

**Comment by simonjbeaumont** [comment]
No, the opposite problem:

```
++./xenvm.native format /home/travis/build/xapi-project/xenvm/bigdisk --vg djstest --configdir /tmp/xenvm.d --mock-devmapper
xenvm: option `--mock-devmapper' needs an argument
Usage: xenvm format [OPTION]... FILENAMES...
Try `xenvm format --help' or `xenvm --help' for more information.
The command "cp .travis.oasis _oasis && bash -ex .travis-opam.sh && bash -ex .travis.sh" exited with 1.
```

Looks like I didn't update all the other tests to pass an argument with `--mock-devmapper`

It's the tests in `test.sh` and `setup.sh`. Are we actually still wanting these?

**Comment by jonludlam** [comment]
I think they should be replaced with test.native now. They're still useful as an example of how to set up xenvmd and run xenvm commands though - I often stick in an 'exit 0' in the script to get things started, so it's worth fixing them.

**Comment by simonjbeaumont** [comment]
OK, I'll fix them up but can we remove them from the CI? I think there's definite overlap with the two shell scripts and I think the coverage is now a subset of the native test suite.

**Comment by simonjbeaumont** [comment]
Say what?! 

Have we picked up a new integration failure while I've been working on this PR?

```
#=== ERROR while installing xenctrl.0.9.30 ====================================#
# opam-version 1.2.2
# os           linux
# command      ./configure
# path         /home/travis/.opam/system/build/xenctrl.0.9.30
# compiler     system (4.02.3)
# exit-code    1
# env-file     /home/travis/.opam/system/build/xenctrl.0.9.30/xenctrl-11694-29d576.env
# stdout-file  /home/travis/.opam/system/build/xenctrl.0.9.30/xenctrl-11694-29d576.out
# stderr-file  /home/travis/.opam/system/build/xenctrl.0.9.30/xenctrl-11694-29d576.err
### stdout ###
# Looking for xenctrl.h: ok
# Looking for libxl_physinfo.outstanding_pages: missing
# Looking for xen-4.5: missing
# Looking for xc_domain_save generation_id: missing
# Looking for HVM_PARAM_VIRIDIAN: ok
### stderr ###
# File "configure.ml", line 160, characters 2-76:
# Warning 20: this argument will not be used by the function.
# Failure: we can't build anything without libxl from Xen 4.4 or greater
---[ snip ]---
=-=- xenctrl.0.9.30 troobleshooting -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
=> This package relies on external (system) dependencies that may be missing.
   `opam depext xenctrl.0.9.30' may help you find the correct installation for
   your system
```

**Comment by simonjbeaumont** [comment]
Changes in ocaml-xen-lowlevel-libs... @djs55 I'm looking at you ;) Probably this? https://github.com/xapi-project/ocaml-xen-lowlevel-libs/commit/9c78efd7d0f81602ea0be971c8c9afb4d9534eae

**Comment by djs55** [comment]
Yeah, sorry about that. `ocaml-xen-lowlevel-libs` aka `xenctrl` and `xenlight` require Xen 4.4 or greater to build completely. I think it suffices to add `dist: trusty` in the `travis.yml`. The previous behaviour was to silently not build some packages (`xenlight`) which then broke users like `jitsu`.

I wonder why `xenvm` needs Xen headers to build?

**Comment by djs55** [comment]
See if #173 fixes it. Alternatively you could add an opam version
constraint to install `xenctrl` < 0.9.30.

On Thu, Oct 22, 2015 at 7:33 PM, Si Beaumont notifications@github.com
wrote:

> Changes in ocaml-xen-lowlevel-libs... @djs55 https://github.com/djs55
> I'm looking at you ;)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/xapi-project/xenvm/pull/171#issuecomment-150315630.

## 

Dave Scott

**Comment by simonjbeaumont** [comment]
I think it's a transitive dependency on rrdd-plugin. rrdd-plugin supports xenostats but I think we should make that an optional dependency like how many libraries compile without lwt if you don't have it installed already.

**Comment by simonjbeaumont** [comment]
Looks like the `dist: trusty` solves this because #173 is passing on Travis but this is a shame because I was hoping that _this_ pull request could help us move toward using the container build. Ah, well I think I'll merge #173 and try rebuilding this.

**Comment by simonjbeaumont** [comment]
Added an extra commit as I think hitting rebuild on Travis is reusing the same config. If it succeeds I'll drop it and push back.

Looking better. The first line is:

```
Using worker: travis-worker-gce-org-prod-1:1c8255a8-1b57-4704-a701-e732eff43228 (testing-gce-5870b4a3-9817-499c-94b2-976678416a93:travis-ci-mega-trusty-1445287562
```

UPDATE: that worked: https://travis-ci.org/xapi-project/xenvm/builds/86911139. I'll remove the commit and reword the previous to cause a rebuild.

**Comment by djs55** [comment]
Ah shame, it would be good to be able to go full container one day :(

**Comment by simonjbeaumont** [comment]
Thanks for the pointer @djs55! I want so badly to enable caching, these builds are taking >20m.

**Pull request merged**
